music = {
    "lalaland" : "https://youtu.be/oTN7xO6emU0?si=_89p6OwGWdMhRUh4",
    "rose" : "https://www.youtube.com/watch?v=OSZCFFpix2g&list=RDOSZCFFpix2g&start_radio=1",
    "youngandbeautiful" : "https://www.youtube.com/watch?v=o_1aF54DO60&list=RDo_1aF54DO60&start_radio=1",
    "lover" : "https://www.youtube.com/watch?v=-BjZmE2gtdo&list=RD-BjZmE2gtdo&start_radio=1",
    "summer" : "https://www.youtube.com/watch?v=TdrL3QxjyVw&list=RDTdrL3QxjyVw&start_radio=1",
    "love" : "https://www.youtube.com/watch?v=CnEqrgMlWLQ&list=RDCnEqrgMlWLQ&start_radio=1",
    "rockstar" : "https://www.youtube.com/watch?v=uqtn2qdsT9Q&list=RDuqtn2qdsT9Q&start_radio=1",
    "tum ho" : "https://www.youtube.com/watch?v=gkCKTuR-ECI&list=RDgkCKTuR-ECI&start_radio=1",
    "tum" : "https://www.youtube.com/watch?v=PZtFYkMYyJA&list=RDPZtFYkMYyJA&start_radio=1",
    "faasle" : "https://www.youtube.com/watch?v=9sekgEXGm-E&list=RD9sekgEXGm-E&start_radio=1",
    "skyfall" : "https://www.youtube.com/watch?v=DeumyOzKqgI&list=RDDeumyOzKqgI&start_radio=1",
    "ordinary" : "https://www.youtube.com/watch?v=u2ah9tWTkmk&list=RDu2ah9tWTkmk&start_radio=1",
    "teenage" : "https://www.youtube.com/watch?v=98WtmW-lfeE&list=RDGMEMQ1dJ7wXfLlqCjwV0xfSNbA&start_radio=1&rv=u2ah9tWTkmk",
    "please" : "https://www.youtube.com/watch?v=cF1Na4AIecM&list=RDGMEMQ1dJ7wXfLlqCjwV0xfSNbA&index=4",
    "espresso" : "https://www.youtube.com/watch?v=eVli-tstM5E&list=RDGMEMQ1dJ7wXfLlqCjwV0xfSNbA&index=6",
    "gorgeous" : "https://www.youtube.com/watch?v=EUoe7cf0HYw&list=RDGMEMQ1dJ7wXfLlqCjwV0xfSNbA&index=7",
    "anti hero" : "https://www.youtube.com/watch?v=XqN2qFvY64U&list=RDGMEMQ1dJ7wXfLlqCjwV0xfSNbA&index=15",
    "see you again" :"https://www.youtube.com/watch?v=RgKAFK5djSk&list=RDRgKAFK5djSk&start_radio=1",
    "believer" : "https://www.youtube.com/watch?v=7wtfhZwyrcc",
    "shape of you" : "https://www.youtube.com/watch?v=JGwWNGJdvx8&list=RDJGwWNGJdvx8&start_radio=1",
    "sapphaire" : "https://www.youtube.com/watch?v=JgDNFQ2RaLQ&list=RDJgDNFQ2RaLQ&start_radio=1",
    "thunder" : "https://www.youtube.com/watch?v=fKopy74weus&list=RD7wtfhZwyrcc&index=4",
    "bad liar" : "https://www.youtube.com/watch?v=I-QfPUz1es8&list=RDI-QfPUz1es8&start_radio=1",
    "despacito" : "https://www.youtube.com/watch?v=TfkP5ubz1z4&list=RDTfkP5ubz1z4&start_radio=1",
    "perfect" : "https://www.youtube.com/watch?v=2Vv-BfVoq4g&list=RD2Vv-BfVoq4g&start_radio=1",
    "photograph" : "https://www.youtube.com/watch?v=KKQl-pIRQMY&list=RDKKQl-pIRQMY&start_radio=1"

}